title: Sam Kaplan # your name (or website title) here
<> logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Robotics Engineering student at Olin College of Engineering. I love to do anything from rapid prototyping to circuit design and firmware development. But really I just love to make cool stuff!
  <br><br>
  I am currently looking for Spring 2021 and Summer 2021 Internships.  
  <br><br>
  
  [View My Resume](./pdfs/Samuel_Kaplan_Resume_Robotics.pdf)
  
  <a href="https://www.linkedin.com/in/sam-kaplan-026bb8164/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


